import maya.standalone
maya.standalone.initialize("Python")
from maya import cmds, mel
import mtoa.ui.arnoldmenu as arnoldmenu
arnoldmenu.doCreatePhysicalSky()
mel.eval('polySphere -r 1 -sx 20 -sy 20 -ax 0 1 0 -cuv 2 -ch 1;')
mel.eval('camera -centerOfInterest 5 -focalLength 35 -lensSqueezeRatio 1 -cameraScale 1 -horizontalFilmAperture 1.41732 -horizontalFilmOffset 0 -verticalFilmAperture 0.94488 -verticalFilmOffset 0 -filmFit Fill -overscan 1 -motionBlur 0 -shutterAngle 144 -nearClipPlane 0.1 -farClipPlane 10000 -orthographic 0 -orthographicWidth 30 -panZoomEnabled 0 -horizontalPan 0 -verticalPan 0 -zoom 1; objectMoveCommand; cameraMakeNode 1 "";')
mel.eval('setAttr "camera1.translateX" 7.887;')
mel.eval('setAttr "camera1.translateY" 3.109;')
mel.eval('setAttr "camera1.translateZ" -10.728;')
mel.eval('setAttr "camera1.rotateX" -14.4;')
mel.eval('setAttr "camera1.rotateY" 144.679;')
mel.eval('setAttr "camera1.rotateZ" 0;')
mel.eval('polyPlane -w 1 -h 1 -sx 10 -sy 10 -ax 0 1 0 -cuv 2 -ch 1;')
mel.eval('setAttr "pPlane1.translateX" 0;')
mel.eval('setAttr "pPlane1.translateY" -1;')
mel.eval('setAttr "pPlane1.translateZ" 0;')
mel.eval('setAttr "pPlane1.scaleX" 100.5;')
mel.eval('setAttr "pPlane1.scaleY" 100.5;')
mel.eval('setAttr "pPlane1.scaleZ" 100.5;')
mel.eval('file -import -type "mayaBinary"  -ignoreVersion -mergeNamespacesOnClash false -rpr "shader" -options "v=0;"  -pr  -importTimeRange "combine" "C:/Users/support/Desktop/shader.mb";')
cmds.sets(['pSphere1'], e=True, forceElement= "aiStandardSurface1SG")
mel.eval('setAttr "aiStandardSurface1.baseColor" -type double3 0.7578 0.5974 1 ;')
mel.eval('polySphere -r 1 -sx 20 -sy 20 -ax 0 1 0 -cuv 2 -ch 1;')
mel.eval('scale -r 1.189442 1.189442 1.189442 ;')
mel.eval('setAttr "aiSkyDomeLight1.rotateY" -218.554;')
mel.eval('setAttr "aiSkyDomeLightShape1.aiColorTemperature" 12999.999998;')
mel.eval('setAttr "pSphere2.scaleX" 40.926;')
mel.eval('setAttr "pSphere2.scaleY" 40.926;')
mel.eval('setAttr "pSphere2.scaleZ" 40.926;')
cmds.delete('pSphere2.f[240:259]')
cmds.delete('pSphere2.f[360:379]')
cmds.delete('pSphere2.f[240:339]')
cmds.file(rename=r"C:\Users\Loong\Demo/mayaFile.ma")
cmds.file(save=True, type="mayaAscii")
